/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Data.Instrutor;
import Data.MySqlConnector;
import Data.dao.AlunoDao;
import Data.dao.InstrutorDao;
import java.util.List;
import javax.swing.JOptionPane;
import util.ComponentController;

/**
 *
 * @author gabi0
 *
 * Classe que exibe a tela de Administrador. Auxilia no gerenciamento dos
 * instrutores cadastrados no sistema.
 */
public class Administrador extends javax.swing.JFrame {

    //Variável de gerenciamento dos instrutores entre a aplicação e o banco
    private final InstrutorDao instrutorDao = new InstrutorDao();

    //Lista com todos os instrutores cadastrados
    private List<Instrutor> listaDeInstrutores;

    //Armazena o instrutor atualmente selecionado
    private Instrutor instrutorSelecionado;

    /**
     * Construtor que inicializa a tela Administrador.
     */
    public Administrador() {
        //título da tela Administrador
        setTitle("Administrador");
        //Inicializa os componentes da tela
        initComponents();
        //Inicializa o combo box contendo os instrutores cadastrados
        initComboBox();
        //inicia tela no centro
        this.setLocationRelativeTo(null);
    }

    /**
     * Recupera todos os instrutores cadastrados no banco de dados e adiciona no
     * combo box para que possam ser editados.
     */
    private void initComboBox() {
        jComboBox1.removeAllItems();
        listaDeInstrutores = instrutorDao.recuperarInstrutor();
        listaDeInstrutores.forEach((ex) -> {
            jComboBox1.addItem(ex.getNome());
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("EXCLUIR INSTRUTOR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Instrutor");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Nome do instrutor:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Senha:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setEnabled(false);
        jTextField1.setFocusTraversalPolicyProvider(true);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("SALVAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("CANCELAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPasswordField1.setEnabled(false);
        jPasswordField1.setMinimumSize(new java.awt.Dimension(6, 23));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(69, 69, 69)
                        .addComponent(jButton4)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(47, 47, 47))
        );

        jLabel2.getAccessibleContext().setAccessibleName("Nome do instrutor::");
        jLabel4.getAccessibleContext().setAccessibleName("Repeticoes");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (instrutorSelecionado != null) {
            //Deleta o instrutor selecionado. Se deletar corretamente, mostra uma
            //mensagem de sucesso e atualiza-se a lista de instrutores. Senao, mostra
            //mensagem de erro
            //Os alunos deste instrutor passam a ficar sem instrutor
            if (instrutorDao.deletarInstrutor(instrutorSelecionado)) {
                JOptionPane.showMessageDialog(null, "Instrutor deletado com sucesso!");
                initComboBox();
            } else {
                JOptionPane.showMessageDialog(null, "Falha ao deletar instrutor");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um instrutor!");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        /*quando um instrutor for selecionado, recupera a posição do item selecionado
        através do combo box e consequentemente o instrutor selecionado
        preenchendo os campos de acordo com as informações no instrutor.
         */
        int itemSelecionado = jComboBox1.getSelectedIndex();
        if (itemSelecionado >= 0) {
            instrutorSelecionado = listaDeInstrutores.get(itemSelecionado);
            //Habilita os campos e insera as informações correspondentes
            ComponentController.alterarJText(true,
                    instrutorSelecionado.getNome(), jTextField1);
            ComponentController.alterarJText(true,
                    instrutorSelecionado.getSenha(), jPasswordField1);
        } else {
            //Esvazia-se e desabilita os campos
            ComponentController.alterarJText(false, "", jTextField1);
            ComponentController.alterarJText(false, "", jPasswordField1);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //variáveis para pegar conteúdo dos campos de texto referentes as informações do exercício
        String novoNome;
        String novaSenha;

        //pegando conteúdo dos campos de texto
        novoNome = jTextField1.getText();
        novaSenha = jPasswordField1.getText();

        //verificando se algum campo de texto está vazio. Se estiver, mostra mensagem de erro
        if (!novoNome.equals("") && !novaSenha.equals("")) {
            //Atualiza-se as informações do instrutor selecionado de acordo com os campos
            instrutorSelecionado.setNome(novoNome);
            instrutorSelecionado.setSenha(novaSenha);

            //Se o instrutor for atualizado com sucesso, mostra-se mensagem de sucesso
            //e atualiza-se a lista de instrutores na tela, senão, mostra mensagem de erro
            if (instrutorDao.atualizarInstrutor(instrutorSelecionado)) {
                JOptionPane.showMessageDialog(null, "Instrutor atualizado com sucesso!");
                //Atualiza-se as informações no combo box de instrutores
                initComboBox();
            } else {
                JOptionPane.showMessageDialog(null, "Falha ao atualizar instrutor");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Campo vazio");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Cria uma instância da tela Login e a torna visível
        //removendo a tela de Administrador
        MySqlConnector.closeConnection();
        LoginInstrutor login = new LoginInstrutor();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Cria e torna a tela de Administrador visível */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
