/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Data.Exercicio;
import Data.MySqlConnector;
import Data.dao.AlunoExercicioDao;
import Data.dao.ExercicioDao;
import java.util.List;
import javax.swing.JOptionPane;
import util.ComponentController;

/**
 *
 * @author gabi0
 *
 * Classe que exibe a tela de Editar de Exercicio. Auxilia na editagem do mesmo
 * e gerenciamento dos dados.
 */
public class EditarEx extends javax.swing.JFrame {

    //Variável de gerenciamento dos exercícios entre a aplicação e o banco
    private final ExercicioDao exercicioDao = new ExercicioDao();

    //Lista com todos os exercícios cadastrados
    private List<Exercicio> listaDeExercicios;

    //Armazena o exercício atualmente selecionado
    private Exercicio exercicioSelecionado;
    
    //Variável de gerenciamento da relação entre um aluno e seus exercícios entre a aplicação e o banco
    private final AlunoExercicioDao alunoExDao = new AlunoExercicioDao();

    /**
     * Construtor que inicializa a tela Editar Execicio.
     */
    public EditarEx() {
        //título da tela Editar Exercício
        setTitle("Editar Exercício");
        //Inicializa os componentes da tela
        initComponents();
        //Inicializa o combo box contendo os exercícios cadastrados
        initComboBox();
        //inicia tela no centro
        this.setLocationRelativeTo(null);
    }

    /**
     * Recupera todos os exercícios cadastrados no banco de dados e adiciona no
     * combo box para que possam ser editados.
     */
    private void initComboBox() {
        jComboBox1.removeAllItems();
        listaDeExercicios = exercicioDao.recuperarExercicios();
        listaDeExercicios.forEach((ex) -> {
            jComboBox1.addItem(ex.getNome());
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Exercício");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Nome do exercício:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Repetições:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setEnabled(false);
        jTextField1.setFocusTraversalPolicyProvider(true);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Séries:");

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.setEnabled(false);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField3.setEnabled(false);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("SALVAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("CANCELAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("EXCLUIR EXERCÍCIO");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(69, 69, 69)
                        .addComponent(jButton4)
                        .addGap(47, 47, 47))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        /*quando um exercício for selecionado, recupera a posição do item selecionado
        através do combo box e consequentemente o exercicio selecionado 
        preenchendo os campos de acordo com as informações no exercício.
         */
        int itemSelecionado = jComboBox1.getSelectedIndex();
        if (itemSelecionado >= 0) {
            exercicioSelecionado = listaDeExercicios.get(itemSelecionado);
            //Habilita os campos e insera as informações correspondentes
            ComponentController.alterarJText(true,
                    exercicioSelecionado.getNome(), jTextField1);
            ComponentController.alterarJText(true,
                    exercicioSelecionado.getRepeticoes(), jTextField2);
            ComponentController.alterarJText(true,
                    exercicioSelecionado.getSerie(), jTextField3);
        } else {
            //Esvazia-se e desabilita os campos
            ComponentController.alterarJText(false, "", jTextField1);
            ComponentController.alterarJText(false, "", jTextField2);
            ComponentController.alterarJText(false, "", jTextField3);
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //variáveis para pegar conteúdo dos campos de texto referentes as informações do exercício
        String novoNome;
        String novoRepeticoes;
        String novoSerie;

        //pegando conteúdo dos campos de texto
        novoNome = jTextField1.getText();
        novoRepeticoes = jTextField2.getText();
        novoSerie = jTextField3.getText();

        //verificando se algum campo de texto está vazio. Se estiver, mostra mensagem de erro
        if (!novoNome.equals("") && !novoRepeticoes.equals("") && !novoSerie.equals("")) {
            //Atualiza-se as informações do exercício selecionado de acordo com os campos
            exercicioSelecionado.setNome(novoNome);
            exercicioSelecionado.setRepeticoes(novoRepeticoes);
            exercicioSelecionado.setSerie(novoSerie);

            //Se o exercício for atualizado com sucesso, mostra-se mensagem de sucesso
            //e atualiza-se a lista de exercícios na tela, senão, mostra mensagem de erro
            if (exercicioDao.atualizarExercicio(exercicioSelecionado)) {
                JOptionPane.showMessageDialog(null, "Exercício atualizado com sucesso!");
                //Atualiza-se as informações no combo box de alunos
                initComboBox();
            } else {
                JOptionPane.showMessageDialog(null, "Falha ao atualizar exercício");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Campo vazio");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Cria uma instância da tela Principal e a torna visível
        //removendo a tela de Editar Exercício
        MySqlConnector.closeConnection();
        Principal p4 = new Principal();
        p4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (exercicioSelecionado != null) {
            //Deleta o exercício selecionado. Se deletar corretamente, mostra uma
            //mensagem de sucesso e atualiza-se a lista de exercícios. Senao, mostra 
            //mensagem de erro
            if (alunoExDao.removerExercicio(exercicioSelecionado.getId()) && 
                    exercicioDao.deletarExercicio(exercicioSelecionado)) {
                JOptionPane.showMessageDialog(null, "Exercício deletado com sucesso!");
                initComboBox();
            } else {
                JOptionPane.showMessageDialog(null, "Falha ao deletar exercício");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um exercício!");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Cria e torna a tela de Editar Exercicio visível */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new EditarEx().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
